Vagrant.configure("2") do |config|
  # Configuración para la máquina "srven"
  config.vm.define "srven" do |srven|
      srven.vm.box = "gusztavvargadr/ubuntu-server-2204-lts"
      srven.vm.network "public_network", bridge: "Puente"
      srven.vm.network "private_network", ip: "192.168.2.1", type: "internal"
      srven.vm.network "private_network", ip: "192.168.100.1", type: "internal"
      srven.vm.provision "shell", path: "SCRIPT-SRVENR.sh"
      srven.vm.provider :hyperv do |hv|
    end
  end

  # Configuración para la máquina "odoo"
  config.vm.define "odoo" do |odoo|
      odoo.vm.box = "gusztavvargadr/ubuntu-server-2204-lts"
      odoo.vm.network "private_network", ip: "192.168.2.2", type: "internal"
      odoo.vm.provision "shell", path: "SCRIPT-ODOO17.sh"
      odoo.vm.provider :hyperv do |hv|
    end
  end

  # Configuración para la máquina "medpot"
  config.vm.define "medpot" do |medpot|
      medpot.vm.box = "sebgarsai/medpot"
      medpot.vm.network "private_network", ip: "192.168.100.2", type: "internal"
      medpot.vm.provision "shell", path: "SCRIPT-MEDPOT.sh"
      medpot.vm.provider :hyperv do |hv|
    end
  end
end